version: "3"

volumes:
  dependency-track-data:

services:
  dependency-track:
    image: owasp/dependency-track:snapshot
    ports:
      - "8081:8080"
    volumes:
      - "dependency-track-data:/data"
    restart: unless-stopped

  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: owasp/dependency-track-frontend:snapshot
    depends_on:
      - dependency-track
    environment:
      - "API_BASE_URL=http://localhost:8081"
      # - "OIDC_ISSUER="
      # - "OIDC_CLIENT_ID="
      # - "OIDC_FLOW="
    # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "8080:80"
    restart: unless-stopped

